<a href="https://colab.research.google.com/github/SohomCh/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [6]:
my_arr=np.array([[1,2,3,4]])

In [7]:
my_arr

array([[1, 2, 3, 4]])

In [8]:
my_arr.shape

(1, 4)

In [9]:
my_arr.dtype

dtype('int64')

In [10]:
### ARRAY FORMATION USING OTHER DATASTRUCTERS

In [12]:
Three_dim = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
Three_dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
Three_dim.shape

(3, 3)

In [15]:
###INTRINSIC CREATION METHODS OF ARRAY

In [19]:
zeros=np.zeros((3,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
ones=np.ones((2,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
range= np.arange(15)
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
range_from_to=np.arange(15,30)
range_from_to

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [35]:
even_till_20=np.arange(0,40,2)
even_till_20

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [30]:
lspace=np.linspace(1,4,4)

In [31]:
lspace

array([1., 2., 3., 4.])

In [33]:
lspace_2=np.linspace(1,10,5)
lspace_2

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
even_till_20.reshape(4,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [38]:
###                NUMPY AXIS

In [43]:
x= np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

from re import A
ar=np.array(x)
ar.sum(axis=0)

In [42]:
ar=np.array(x)
ar.sum(axis=0)

array([12, 15, 18])

In [44]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [48]:
one=np.array([1,2,444,5,0,7,8])

one.argmin()

np.int64(4)

In [47]:
one.argmax()

np.int64(2)